runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(.+)/
  static_files: public/\1/index.html
  upload: public/(.+)/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
  secure: always
  redirect_http_response_code: 301

skip_files:
- (?!^public)