apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: elx-docs

# Labels is handled by the metadataLabelTransformer just add your labels :)

resources:
  - default-networkpolicies.yaml
  - networkpolicies.yaml
  - deployment.yaml
  - ingress.yaml
  - issuer.yaml
  - namespace.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: quay.io/elastx/elx-docs
    newTag: latest

configMapGenerator:
  - name: elx-docs-config
    files:
      - config.toml

transformers:
- metadataLabelTransformer.yaml
