apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: elx-docs

commonLabels:
  app.kubernetes.io/name: elx-docs
  app.kubernetes.io/version: 0.0.1

resources:
  - deployment.yaml
  - ingress.yaml
  - issuer.yaml
  - namespace.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: quay.io/elastx/elx-docs
    newTag: latest

configMapGenerator:
  - name: elx-docs-config
    files:
      - config.toml
