apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  app.kubernetes.io/name: elx-docs
  app.kubernetes.io/version: 0.0.1
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: false